# Generated by Django 4.2 on 2023-05-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_product_purchase_purchasereturns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length='100', upload_to='upload/'),
        ),
    ]
